export * from './add-project-task/AddProjectTask';
export * from './analytics/Analytics';
export * from './authorization/authorization';
export * from './edit-task/EditTask';
export * from './home/Home';
export * from './info/Info-page';
export * from './profile/ProfilePage';
export * from './projects/Projects';
export * from './registration/registration';
